parameters:
  env(ROCKETGATE_ADMIN_LOGIN): ''
  env(ROCKETGATE_ADMIN_PASSWORD): ''

services:
  rocketgate.report.gateway:
    class: SymfonyLab\RocketGateReport\GatewayService
    arguments:
      - '%env(ROCKETGATE_ADMIN_LOGIN)%'
      - '%env(ROCKETGATE_ADMIN_PASSWORD)%'

  SymfonyLab\RocketGateReportBundle\Repository\SubscriptionRepository:
    arguments:
      - '@rocketgate.report.gateway'

  SymfonyLab\RocketGateReportBundle\Command\ShowSubscriptionByCustomerCommand:
    arguments:
      - '@SymfonyLab\RocketGateReportBundle\Repository\SubscriptionRepository'
    tags: ['console.command']
