parameters:
  env(ROCKETGATE_ADMIN_LOGIN): ''
  env(ROCKETGATE_ADMIN_PASSWORD): ''

services:
  Nevmmv\RocketGate\GatewayService:
    arguments:
      - '%env(ROCKETGATE_ADMIN_LOGIN)%'
      - '%env(ROCKETGATE_ADMIN_PASSWORD)%'

  SymfonyLab\RocketGateReportBundle\Repository\SubscriptionRepository:
  SymfonyLab\RocketGateReportBundle\Command\ShowSubscriptionByCustomerCommand:
    arguments:
      - '@SymfonyLab\RocketGateReportBundle\Repository\SubscriptionRepository'
    tags: ['console.command']
